[tool.poetry]
name = "tests"
version = "0.1.0"
description = ""
authors = ["Dong Liang <ldifer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.1.2"
MarkupSafe = "^2.1.1"
api = "^0.0.7"
marshmallow = "^3.17.0"
joblib = "^1.1.0"
Flask = "^2.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
