name: config file 

on: push

jobs:
  setup-docker-env:
    uses: DongL/deploying-machine-learning-models/.github/workflows/docker-setup.yml@mle
  prepare-venv: 
    needs: setup-docker-env
    uses: DongL/deploying-machine-learning-models/.github/workflows/prepare-venv.yml@mle
  prepare-tox: 
    needs: prepare-venv
    uses: DongL/deploying-machine-learning-models/.github/workflows/prepare-tox.yml@mle