name: config file 

on: push

jobs: 
  docker-setup:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9.13-alpine3.14
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: log python version 
        run: |
          python --version

      - name: create venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip 
          python --version

      - name: Install tox
        run: |
          # sudo pip install --upgrade pip
          pip install --user tox

      - name: test_app
        run: | 
          cd section-07-ci-and-publishing/house-prices-api
          /github/home/.local/lib/python3.9/site-packages/tox






  # setup-docker-env:
  #   uses: DongL/deploying-machine-learning-models/.github/workflows/docker-setup.yml@mle
  # prepare-venv: 
  #   needs: setup-docker-env
  #   uses: DongL/deploying-machine-learning-models/.github/workflows/prepare-venv.yml@mle
  # prepare-tox: 
  #   needs: setup-docker-env
  #   uses: DongL/deploying-machine-learning-models/.github/workflows/prepare-tox.yml@mle
  # sanity-check:
  #   runs-on: ubuntu-latest
  #   needs: prepare-tox
  #   steps:
  #     - name: log python version
  #       run: |
  #         python --version


    