name: differential test 
on: push 
  # workflow_call:
  # workflow_dispatch:
      
jobs: 
  section_9_differential_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip 
          python --version

      - name: Capture previous model predictions
        run: | 
          . venv/bin/activate
          pip install -r packages/ml_api/diff_test_requirements.txt
          PYTHONPATH=./packages/ml_api python3 packages/ml_api/tests/capture_model_predictions.py
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          GEMFURY_PUSH_URL: ${{ secrets.GEMFURY_PUSH_URL }}
          PIP_EXTRA_INDEX_URL: ${{ secrets.PIP_EXTRA_INDEX_URL }}

      - name: Runnning differential tests
        run: | 
          . venv/bin/activate
          pip install -r packages/ml_api/requirements.txt
          py.test -vv packages/ml_api/tests -m differential
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          GEMFURY_PUSH_URL: ${{ secrets.GEMFURY_PUSH_URL }}
          PIP_EXTRA_INDEX_URL: ${{ secrets.PIP_EXTRA_INDEX_URL }}
