name: ML-config
on: 
   workflow_call:
   workflow_dispatch:
      


jobs:
  docker-setup:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9.13-alpine3.14
    steps:
      - name: log docker 
        run: |
          echo 'Docker image installed!'
      - name: log python version
        run: | 
          python --version

      # working_directory: ~/project

  

