name: docker image - deployment
on: push 
  # workflow_call:
  # workflow_dispatch:
      


jobs:
  deploy_app_container_in_heroku:
    runs-on: ubuntu-latest
    # container: 
    #   image: python:3.9.13-alpine3.14
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker setup
        uses: docker-practice/actions-setup-docker@master
      - name: build image
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          GEMFURY_PUSH_URL: ${{ secrets.GEMFURY_PUSH_URL }}
          PIP_EXTRA_INDEX_URL: ${{ secrets.PIP_EXTRA_INDEX_URL }}
        run: |
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          cd section-08-deploying-with-containers && make build-ml-api-heroku
      - name: push image to Heroku image registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }} 
        run: |
          cd section-08-deploying-with-containers && make push-ml-api-heroku
      - name: release to Heroku
        run: |
          cd section-08-deploying-with-containers && make release-heroku


      # working_directory: ~/project

  

