name: docker setup 
on: push 
  # workflow_call:
  # workflow_dispatch:
      


jobs:
  deploy_app_container_in_heroku:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9.13-alpine3.14
    steps:
      - name: log docker 
        run: |
          echo 'Docker image installed!'
      - name: log python version
        run: | 
          python --version
      - name: checkout
        uses: actions/checkout@v3
      - name: build image
        run: |
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          cd section-08-deploying-with-containers && make build-ml-api-heroku


      # working_directory: ~/project

  

