name: docker image - deployment
on: push 
  # workflow_call:
  # workflow_dispatch:
      


jobs:
  deploy_app_container_in_heroku:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9.13-alpine3.14
    steps:
      - name: docker container
        uses: docker://node:12.14.1-alpine3.10
      - name: checkout
        uses: actions/checkout@v3
      - name: setup docker
        uses: docker-practice/actions-setup-docker@master
        run: |
          set -x 
          docker version
          docker run --rm hello-world    
      - name: build image
        run: |
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          cd section-08-deploying-with-containers && make build-ml-api-heroku


      # working_directory: ~/project

  

