name: prepare venv
on: 
   workflow_call:
   workflow_dispatch:

jobs:
  # setup-docker-env:
  #   uses: DongL/deploying-machine-learning-models/.github/workflows/docker-setup.yml@mle

  prepare-python:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9.13-alpine3.14
    steps: 
      - name: log python version 
        run: |
          python --version
      - name: create venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
