name: prepare venv
on: push

jobs:
  setup-docker-env:
    uses: DongL/deploying-machine-learning-models/.github/workflows/docker-setup.yml@main

  setup-python-env:
    runs-on: ubuntu-latest
    steps: 
      - name: log python version 
        run: |
          python --version
      - name: create venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
